WebMVC/Controllers/CategoriaMaterialController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjectModel.Entities;
using ProjectModel.Models;

namespace WebMVC.Controllers
{
    public class CategoriaMaterialController : Controller
    {
        BLCategoriaMaterial bLCategoriaMaterial = new BLCategoriaMaterial(ConfigurationManager.ConnectionStrings["con"].ConnectionString);

        // Método para la tabla con los datos (Home)
        public ActionResult Mostrar()
        {
            List<CategoriaMaterial> categories = null;
            string msj = "";
            categories = bLCategoriaMaterial.ObtenerCategorias(ref msj);
            return View(categories);
        }


        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Agregar()
        {
            string msj = "";

            CategoriaMaterial categoria = new CategoriaMaterial()
            {
                nomCategoria = Request.Form["txtNom"],
                extra = Request.Form["txtExt"],
            };


            bLCategoriaMaterial.InsertarCategoria(categoria, ref msj);
            // Recargar los datos antes de redirigir a la vista Mostrar
            List<CategoriaMaterial> categories = null;
            categories = bLCategoriaMaterial.ObtenerCategorias(ref msj);

            // Devolver la vista Mostrar con los datos actualizados
            return View("Mostrar", categories);
        }

        public ActionResult Edit(string id)
        {
            string msj = "";
            ViewBag.id = id;

            CategoriaMaterial categoria = new CategoriaMaterial();
            categoria = bLCategoriaMaterial.CategoriaMaterialPorId(int.Parse(id), ref msj);
            return View(categoria);
        }

        public ActionResult Editar()
        {
            string msj = "";

            CategoriaMaterial categoria = new CategoriaMaterial()
            {
                idCategoria = int.Parse(Request.Form["ID"]),
                nomCategoria = Request.Form["txtNom"],
                extra = Request.Form["txtExt"],
            };


            bLCategoriaMaterial.EditarCategoria(categoria, ref msj);
            // Recargar los datos antes de redirigir a la vista Mostrar
            List<CategoriaMaterial> categories = null;
            categories = bLCategoriaMaterial.ObtenerCategorias(ref msj);

            // Devolver la vista Mostrar con los datos actualizados
            return View("Mostrar", categories);

        }


        public ActionResult Eliminar(int id)
        {
            string msj = "";
            CategoriaMaterial categoria = new CategoriaMaterial()
            {
                idCategoria = id
            };

            bLCategoriaMaterial.EliminarCategoria(categoria, ref msj);
            List<CategoriaMaterial> categories = null;
            categories = bLCategoriaMaterial.ObtenerCategorias(ref msj);
            return View("Mostrar", categories);
        }


    }
}

WebMVC/Controllers/MaterialController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjectModel.Entities;
using ProjectModel.Models;

namespace WebMVC.Controllers
{
    public class MaterialController : Controller
    {
        BLMaterial bLMaterial = new BLMaterial(ConfigurationManager.ConnectionStrings["con"].ConnectionString);
        
        // Método para la tabla con los datos (Home)
        public ActionResult Mostrar()
        {
            List<Material> materials = null;
            string msj = "";
            materials = bLMaterial.ObtenerMateriales(ref msj);
            return View(materials);
        }




        // Método para traer la vista crear
        public ActionResult Create()
        {
            // Mensaje de referencia
            string msj = "";

            // Lista de datos para el DropDownList
            BLCategoriaMaterial bLCategoriaMaterial = new BLCategoriaMaterial(ConfigurationManager.ConnectionStrings["con"].ConnectionString);
            List<CategoriaMaterial> categories = null;
            categories = bLCategoriaMaterial.ObtenerCategorias(ref msj);

            // Lista de Items con los datos anteriores
            List<SelectListItem> items =  new List<SelectListItem>();

            // Llenado de la lista SelectedItem
            foreach(CategoriaMaterial c in  categories)
            {
                items.Add(new SelectListItem
                {
                    Value = c.idCategoria.ToString(),
                    Text = c.nomCategoria,
                });
            }
            ViewBag.listaDrop = items;

            return View();
        }

        public ActionResult Edit(string id)
        {
            // Mensaje de referencia
            string msj = "";

            // Lista de datos para el DropDownList
            BLCategoriaMaterial bLCategoriaMaterial = new BLCategoriaMaterial(ConfigurationManager.ConnectionStrings["con"].ConnectionString);
            List<CategoriaMaterial> categories = null;
            categories = bLCategoriaMaterial.ObtenerCategorias(ref msj);

            // Lista de Items con los datos anteriores
            List<SelectListItem> items = new List<SelectListItem>();

            // Llenado de la lista SelectedItem
            foreach (CategoriaMaterial c in categories)
            {
                items.Add(new SelectListItem
                {
                    Value = c.idCategoria.ToString(),
                    Text = c.nomCategoria,
                });
            }
            ViewBag.listaDrop = items;
            ViewBag.id = id;

            Material material = new Material();
            material = bLMaterial.MaterialPorId(int.Parse(id), ref msj);


            return View(material);
        }

        public ActionResult Editar()
        {
            string msj = "";

            Material material = new Material()
            {
                Idmaterial = int.Parse(Request.Form["ID"]),
                NombreMat = Request.Form["txtNom"],
                Marca = Request.Form["txtMar"],
                Categoria = Request.Form["txtCat"],
                UnidadMedida = Request.Form["txtUni"]
            };


            bLMaterial.EditarMaterial(material, ref msj);
            // Recargar los datos antes de redirigir a la vista Mostrar
            List<Material> materials = null;
            materials = bLMaterial.ObtenerMateriales(ref msj);

            // Devolver la vista Mostrar con los datos actualizados
            return View("Mostrar", materials);
        }

        public ActionResult Agregar()
        {
            string msj = "";

            Material material = new Material()
            {
                NombreMat = Request.Form["txtNom"],
                Marca = Request.Form["txtMar"],
                Categoria = Request.Form["txtCat"],
                UnidadMedida = Request.Form["txtUni"]
            };


            bLMaterial.InsertarMaterial(material, ref msj);
            // Recargar los datos antes de redirigir a la vista Mostrar
            List<Material> materials = null;
            materials = bLMaterial.ObtenerMateriales(ref msj);

            // Devolver la vista Mostrar con los datos actualizados
            return View("Mostrar", materials);
        }


        public ActionResult Eliminar(int id)
        {
            string msj = "";
            Material material = new Material()
            {
                Idmaterial = id
            };

            bLMaterial.EliminarMaterial(material, ref msj);
            List<Material> materials  = null;
            materials = bLMaterial.ObtenerMateriales(ref msj);
            return View("Mostrar", materials);
        }


    }
}

WebMVC/Controllers/contrareciboController.cs
using ProjectModel.Entities;
using ProjectModel.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebMVC.Controllers
{
    public class contrareciboController : Controller
    {

        BLContrarecibo bLContrarecibo = new BLContrarecibo(ConfigurationManager.ConnectionStrings["con"].ConnectionString);

        // Método para la tabla con los datos (Home)
        public ActionResult Mostrar()
        {
            List<Contrarecibo> recibo = null;
            string msj = "";
            recibo = bLContrarecibo.ObtenerContrarecibo(ref msj);
            return View(recibo);
        }


        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Agrega()
        {
            string msj = "";

            Contrarecibo recibo = new Contrarecibo()
            {
                fecha = Request.Form["txtfecha"],
                obra = Request.Form["txtobra"],
                extra = Request.Form["txtExt"],
            };


            bLContrarecibo.InsertarContrarecibo(recibo, ref msj);
            // Recargar los datos antes de redirigir a la vista Mostrar
            List<Contrarecibo> recibos = null;
            recibos = bLContrarecibo.ObtenerContrarecibo(ref msj);

            // Devolver la vista Mostrar con los datos actualizados
            return View("Mostrar", recibos);
        }

        public ActionResult Edit(string id)
        {
            string msj = "";
            ViewBag.id = id;

            Contrarecibo contra = new Contrarecibo();
            contra = bLContrarecibo.ContrareciboPorId(int.Parse(id), ref msj);
            return View(contra);
        }

        public ActionResult Editar()
        {
            string msj = "";

            Contrarecibo recibo = new Contrarecibo()
            {
                id = int.Parse(Request.Form["ID"]),
                fecha = Request.Form["txtfecha"],
                obra = Request.Form["txtobra"],
                extra = Request.Form["txtExt"],

            };


            bLContrarecibo.EditarContrarecibo(recibo, ref msj);
            // Recargar los datos antes de redirigir a la vista Mostrar
            List<Contrarecibo> recibos = null;
            recibos = bLContrarecibo.ObtenerContrarecibo(ref msj);

            // Devolver la vista Mostrar con los datos actualizados
            return View("Mostrar", recibos);

        }

        public ActionResult Eliminar(int id)
        {
            string msj = "";
            Contrarecibo recibo = new Contrarecibo()
            {
                id = id
            };

            bLContrarecibo.EliminarContrarecibo(recibo, ref msj);
            List<Contrarecibo> recibos = null;
            recibos = bLContrarecibo.ObtenerContrarecibo(ref msj);
            return View("Mostrar", recibos);
        }


    }
}

WebMVC/Controllers/detalleContrareciboController.cs
using ProjectModel.Entities;
using ProjectModel.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebMVC.Controllers
{
    public class detalleContrareciboController : Controller
    {

        BLDetalleContrarecibo bLdetalleContrarecibo = new BLDetalleContrarecibo(ConfigurationManager.ConnectionStrings["con"].ConnectionString);

        // Método para la tabla con los datos (Home)
        public ActionResult Mostrar()
        {
            List<detalleContrarecibo> recibo = null;
            string msj = "";
            recibo = bLdetalleContrarecibo.ObtenerDetaleContrarecibo(ref msj);
            return View(recibo);
        }


        public ActionResult Create()
        {
            // Mensaje de referencia
            string msj = "";

            // Lista de datos para el DropDownList
            BLNota bLnotas = new BLNota(ConfigurationManager.ConnectionStrings["con"].ConnectionString);
            List<nota> notas = null;
            notas = bLnotas.Obtenernota(ref msj);

            BLContrarecibo bLcontra = new BLContrarecibo(ConfigurationManager.ConnectionStrings["con"].ConnectionString);
            List<Contrarecibo> contrarecibos = null;
            contrarecibos = bLcontra.ObtenerContrarecibo(ref msj);

            // Lista de Items con los datos anteriores
            List<SelectListItem> items = new List<SelectListItem>();
            List<SelectListItem> items2 = new List<SelectListItem>();

            // Llenado de la lista SelectedItem
            foreach (nota c in notas)
            {
                items.Add(new SelectListItem
                {
                    Value = c.Id.ToString(),
                    Text = $"{"Numero de nota: " + c.Numeronota} - {" Fecha de nota: " + c.fecha}"
                });
            }
            foreach (Contrarecibo c in contrarecibos)
            {
                items2.Add(new SelectListItem
                {
                    Value = c.id.ToString(),
                    Text = $"{"Fecha de contrarecibo: " + c.fecha} - {"Obra: " + c.obra}",
                });
            }
            ViewBag.listaDrop = items;
            ViewBag.listaDrop2 = items2;
            return View();
        }

        public ActionResult Agregar()
        {
            string msj = "";

            detalleContrarecibo recibo = new detalleContrarecibo()
            {
                contrarecibo = Request.Form["txtcontrarecibo"],
                nota = Request.Form["txtnota"],
                total = Request.Form["txttotal"],
                pagada = Request.Form["txtpagada"],
            };


            bLdetalleContrarecibo.InsertarDetalleContrarecibo(recibo, ref msj);
            // Recargar los datos antes de redirigir a la vista Mostrar
            List<detalleContrarecibo> recibos = null;
            recibos = bLdetalleContrarecibo.ObtenerDetaleContrarecibo(ref msj);

            // Devolver la vista Mostrar con los datos actualizados
            return View("Mostrar", recibos);
        }

        public ActionResult Edit(string id)
        {
            // Mensaje de referencia
            string msj = "";

            // Lista de datos para el DropDownList
            BLNota bLnotas = new BLNota(ConfigurationManager.ConnectionStrings["con"].ConnectionString);
            List<nota> notas = null;
            notas = bLnotas.Obtenernota(ref msj);

            BLContrarecibo bLcontra = new BLContrarecibo(ConfigurationManager.ConnectionStrings["con"].ConnectionString);
            List<Contrarecibo> contrarecibos = null;
            contrarecibos = bLcontra.ObtenerContrarecibo(ref msj);

            // Lista de Items con los datos anteriores
            List<SelectListItem> items = new List<SelectListItem>();
            List<SelectListItem> items2 = new List<SelectListItem>();

            // Llenado de la lista SelectedItem
            foreach (nota c in notas)
            {
                items.Add(new SelectListItem
                {
                    Value = c.Id.ToString(),
                    Text = $"{"Numero de nota: "+c.Numeronota} - {" Fecha de nota: "+c.fecha}"
                }) ;
            }
            foreach (Contrarecibo c in contrarecibos)
            {
                items2.Add(new SelectListItem
                {
                    Value = c.id.ToString(),
                    Text = $"{"Fecha de contrarecibo: "+c.fecha} - {"Obra: "+c.obra}",
                });
            }
            ViewBag.listaDrop = items;
            ViewBag.listaDrop2 = items2;
            ViewBag.id = id;

            detalleContrarecibo contra = new detalleContrarecibo();
            contra = bLdetalleContrarecibo.detallereciboPorId(int.Parse(id), ref msj);
            return View(contra);
        }

        public ActionResult Editar()
        {
            string msj = "";

            detalleContrarecibo recibo = new detalleContrarecibo()
            {
                id = int.Parse(Request.Form["ID"]),
                contrarecibo = Request.Form["txtcontrarecibo"],
                nota = Request.Form["txtnota"],
                total = Request.Form["txttotal"],
                pagada = Request.Form["txtpagada"],
            };


            bLdetalleContrarecibo.EditarDetalleContrarecibo(recibo, ref msj);
            // Recargar los datos antes de redirigir a la vista Mostrar
            List<detalleContrarecibo> recibos = null;
            recibos = bLdetalleContrarecibo.ObtenerDetaleContrarecibo(ref msj);

            // Devolver la vista Mostrar con los datos actualizados
            return View("Mostrar", recibos);

        }

        public ActionResult Eliminar(int id)
        {
            string msj = "";
            detalleContrarecibo recibo = new detalleContrarecibo()
            {
                id = id
            };

            bLdetalleContrarecibo.EliminarDetalleContrarecibo(recibo, ref msj);
            List<detalleContrarecibo> recibos = null;
            recibos = bLdetalleContrarecibo.ObtenerDetaleContrarecibo(ref msj);
            return View("Mostrar", recibos);
        }

    }
}

WebMVC/Views/detalleContrarecibo/Create.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="~/CSS/StyleSheet1.css" type="text/css" rel="stylesheet" />
</head>
<body>
    <div class="bg-primary bg-gradient">
        <nav class="navigation container">

            <a href="@Url.Action("Mostrar", "Material")">Materiales</a>
            <a href="@Url.Action("Mostrar", "CategoriaMaterial")">Categoria</a>
            <a href="@Url.Action("Mostrar","contrarecibo")">Contrarecibo</a>
            <a href="@Url.Action("Mostrar","detalleContrarecibo")">DetalleContrarecibo</a>
        </nav>
    </div>

    <div class="container">
        <h1>Agregar DetalleContrarecibo</h1>

        <form action="Agregar" method="post">

            <div class="form-group">
                <label>Contrarecibo: </label>
                @Html.DropDownList("txtcontrarecibo", (List<SelectListItem>)ViewBag.listaDrop2, new { @class = "form-control" })
            </div>

            <div class="form-group">

                <label>Nota: </label>
                @Html.DropDownList("txtnota", (List<SelectListItem>)ViewBag.listaDrop, new { @class = "form-control" })
            </div>

            <div class="form-group">

                <label>Total: </label>
                <input type="text" name="txttotal" class="form-control" />
            </div>

            <div class="form-group">

                <label>pagada: </label>
                <input type="radio" name="txtpagada" value="1"> Si
                <input type="radio" name="txtpagada" value="0"> No

            </div>

            <input type="submit" value="Insertar DetalleContrarecibo" class="btn btn-primary" />

        </form>
    </div>
</body>
</html>

WebMVC/Views/detalleContrarecibo/Edit.cshtml
@model ProjectModel.Entities.detalleContrarecibo
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="~/CSS/StyleSheet1.css" type="text/css" rel="stylesheet" />
</head>
<body>

    <div class="bg-primary bg-gradient">
        <nav class="navigation container">

            <a href="@Url.Action("Mostrar", "Material")">Materiales</a>
            <a href="@Url.Action("Mostrar", "CategoriaMaterial")">Categoria</a>
            <a href="@Url.Action("Mostrar","contrarecibo")">Contrarecibo</a>
            <a href="@Url.Action("Mostrar","detalleContrarecibo")">DetalleContrarecibo</a>
        </nav>
    </div>


    <div class="container">

        <form action="@Url.Action("Editar", "detalleContrarecibo")" method="post">
            <h1>Modificando DetalleContrarecibo con el ID:</h1>
            <input type="number" value="@ViewBag.id" name="ID" />

            <div class="form-group">
                <label>Contrarecibo: </label>
                @Html.DropDownList("txtcontrarecibo", (List<SelectListItem>)ViewBag.listaDrop2, new { @class = "form-control" })
            </div>

            <div class="form-group">

                <label>Nota: </label>
                @Html.DropDownList("txtnota", (List<SelectListItem>)ViewBag.listaDrop, new { @class = "form-control" })
            </div>

            <div class="form-group">

                <label>Total: </label>
                <input type="number" name="txttotal" class="form-control" value="@Model.total" />
            </div>

            <div class="form-group">
                <label>pagada: </label>
                <input type="radio" name="txtpagada" value="1"> Si
                <input type="radio" name="txtpagada" value="0"> No

            </div>
            <div></div>
            <input type="submit" value="Insertar DetalleContrarecibo" class="btn btn-primary" />
        </form>
    </div>

</body>
</html>

WebMVC/Views/detalleContrarecibo/Mostrar.cshtml
@model IEnumerable<ProjectModel.Entities.detalleContrarecibo>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Mostrar</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="~/CSS/StyleSheet1.css" type="text/css" rel="stylesheet" />

</head>
<body>
    <div class="bg-primary bg-gradient">
        <nav class="navigation container">

            <a href="@Url.Action("Mostrar", "Material")">Materiales</a>
            <a href="@Url.Action("Mostrar", "CategoriaMaterial")">Categoria</a>
            <a href="@Url.Action("Mostrar","contrarecibo")">Contrarecibo</a>
            <a href="@Url.Action("Mostrar","detalleContrarecibo")">DetalleContrarecibo</a>
        </nav>
    </div>
    <div class="container">
        <h1>DETALLE DE CONTRARECIBO</h1>
        <a href="@Url.Action("Create", "detalleContrarecibo")" class="btn btn-success">Agregar Detalle</a>

    </div>
    <table class="table table-striped container">

        <tr>
            <th>
                @Html.DisplayNameFor(model => model.id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.contrarecibo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.fecha_recibo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.obra)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nota)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.fecha_nota)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.total)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.pagada)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.contrarecibo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fecha_recibo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.obra)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.nota)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fecha_nota)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.total)
                </td>
                <td>
                    @if (int.Parse(item.pagada) == 1)
                    {
                        <text>pagado</text>
                    }
                    else if (int.Parse(item.pagada) == 0)
                    {
                        <text>no pagado</text>
                    }
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.id }, new { @class = "btn btn-warning" }) |
                    @Html.ActionLink("Eliminar", "Eliminar", new { id = item.id }, new { @class = "btn btn-danger" })
                </td>
            </tr>
        }

    </table>
</body>
</html>